---
title: "Problema 1 - Checkpoint 1 - Nossa Pergunta"
author: "Matheus Freitas"
date: "23 de abril de 2018"
output:
  html_notebook:
    toc: yes
    toc_float: yes
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(here)
theme_set(theme_bw())
```

Analisaremos os episódios das séries Vikings, Game of Thrones. 
```{r}
data = read_csv(here("data/series_from_imdb.csv"),
                   progress = FALSE,
                   col_types = cols(.default = col_double(), 
                                     series_name = col_character(), 
                                     episode = col_character(), 
                                     url = col_character(),
                                     season = col_character())) %>%
  filter(series_name %in% c("Vikings", "Game of Thrones"))

```


```{r}
data %>% 
    ggplot(aes(x = season, y = user_rating, color = series_name)) + 
    geom_jitter(width = .05) +
    ylim(5, 10) + 
    labs(x ="Temporadas", y = "Avaliação no IMDB")
```
